from enum import Enum

class ErrorCodes(Enum):
  TASK_NOT_FOUND = "TASK_NOT_FOUND"
  INVALID_ID = "INVALID_ID"
  INTERNAL_ERROR = "INTERNAL_ERROR"
  COMMAND_MISSING = "COMMAND_MISSING"
  REQUEST_BODY_MUST_BE_JSON = "REQUEST_BODY_MUST_BE_JSON"